apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: api-gateway
  labels:
    stage: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: social-network/api-gateway:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ENC_KEY
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: ENC_KEY
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: JWT_KEY
            - name: SENTINEL_ADDRS
              value: redis-sentinel.redis.svc.cluster.local:26379
            - name: REDIS_MASTER_SET
              value: "master"
            - name: TELEMETRY_COLLECTOR_ADDR
              value: "localhost:4317"

            - name: USERS_GRPC_ADDR
              value: "users.users.svc.cluster.local:50051"
            - name: POSTS_GRPC_ADDR
              value: "posts.posts.svc.cluster.local:50051"
            - name: CHAT_GRPC_ADDR
              value: "chat.chat.svc.cluster.local:50051"
            - name: NOTIFICATIONS_GRPC_ADDR
              value: "notifications.notifications.svc.cluster.local:50051"
            - name: MEDIA_GRPC_ADDR
              value: "media.media.svc.cluster.local:50051"

            - name: SHUTDOWN_TIMEOUT_SECONDS
              value: "5"
            - name: ENABLE_DEBUG_LOGS
              value: "true"
            - name: ENABLE_SIMPLE_PRINT
              value: "true"
            - name: KAFKA_BROKERS
              value: "kafka.kafka.svc.cluster.local:29092"
            - name: NATS_CLUSTER
              value: "nats://ruser:T0pS3cr3t@nats-client.messaging.svc.cluster.local:4222"