apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: notifications-db
  namespace: notifications
  labels:
    stage: db
spec:
  instances: 3

  imageName: postgres:16-cloud-native

  bootstrap:
    initdb:
      database: notifications
      owner: postgres

  superuserSecret:
    name: notifications-db-superuser

  storage:
    size: 1Gi
