# apiVersion: v1
# kind: Secret
# metadata:
#   name: notifications-app-secret
#   namespace: notifications
#   labels:
#     stage: config
# type: kubernetes.io/basic-auth
# stringData:
#   username: notifications
#   password: secret
