apiVersion: v1
kind: Secret
metadata:
  name: notifications-app-secret
  namespace: notifications
  labels:
    stage: config
type: Opaque
stringData:
  ENC_KEY: a2F0LWFsZXgtdmFnLXlwYXQtc3RhbS16b25lMDEtZ28=
  DATABASE_URL: "postgres://postgres:secret@notifications-db-rw:5432/notifications?sslmode=disable"
