apiVersion: v1
kind: Secret
metadata:
  name: notifications-db-superuser
  namespace: notifications
  labels:
    stage: config
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: secret
