apiVersion: v1
kind: Secret
metadata:
  name: media-app-secret
  namespace: media
  labels:
    stage: config
type: Opaque
stringData:
  ENC_KEY: a2F0LWFsZXgtdmFnLXlwYXQtc3RhbS16b25lMDEtZ28=
  DATABASE_URL: "postgres://postgres:secret@media-db-rw:5432/media?sslmode=disable"
  MINIO_ACCESS_KEY: bWluaW8=       # base64 of "minio"
  MINIO_SECRET_KEY: bWluaW8xMjM=   # base64 of "minio123"
