# apiVersion: v1
# kind: Secret
# metadata:
#   name: media-app-secret
#   namespace: media
#   labels:
#     stage: config
# type: kubernetes.io/basic-auth
# stringData:
#   username: media
#   password: secret

