apiVersion: v1
kind: Secret
metadata:
  name: media-app-secret
  namespace: media
  labels:
    stage: config
type: Opaque
stringData:
  ENC_KEY: social-network-secret-key
  DATABASE_URL: "postgres://postgres:secret@media-db-rw:5432/media?sslmode=disable"
  MINIO_ACCESS_KEY: minio
  MINIO_SECRET_KEY: minio123
