apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-db
  namespace: forum
  labels:
    stage: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-db
  template:
    metadata:
      labels:
        app: forum-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: forum-secret
                  key: DATABASE_URL
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: forum-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: forum-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: forum-secret
                  key: POSTGRES_PASSWORD
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forum-db-pvc
