apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forum-db-pvc
  namespace: forum
  labels:
    stage: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
