apiVersion: v1
kind: Service
metadata:
  name: forum-db
  namespace: forum
  labels:
    stage: app
spec:
  selector:
    app: forum-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
