apiVersion: apps/v1
kind: Deployment
metadata:
  name: live
  namespace: live
  labels:
    stage: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: live
  template:
    metadata:
      labels:
        app: live
    spec:
      containers:
        - name: live
          image: social-network/live:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ENC_KEY
              valueFrom:
                secretKeyRef:
                  name: live-secret
                  key: ENC_KEY
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: live-secret
                  key: JWT_KEY