apiVersion: v1
kind: Secret
metadata:
  name: live-secret
  namespace: live
  labels:
    stage: config
type: Opaque
data:
  ENC_KEY: a2F0LWFsZXgtdmFnLXlwYXQtc3RhbS16b25lMDEtZ28=  # base64 of "kat-alex-vag-ypat-stam-zone01-go"
  JWT_KEY: a2F0LWFsZXgtdmFnLXlwYXQtc3RhbS16b25lMDEtZ28=  # base64 of "kat-alex-vag-ypat-stam-zone01-go"
