apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: storage
  labels:
    stage: config
type: Opaque
data:
  MINIO_ACCESS_KEY: bWluaW8=       # base64 of "minio"
  MINIO_SECRET_KEY: bWluaW8xMjM=   # base64 of "minio123"