apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: users
  labels:
    stage: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z users-db-rw 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: users
          image: social-network/users:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: users-app-secret
                  key: DATABASE_URL
            - name: ENC_KEY
              valueFrom:
                secretKeyRef:
                  name: posts-app-secret
                  key: ENC_KEY
