apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: users
type: Opaque
stringData:
  POSTGRES_DB: social_users
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret
  DATABASE_URL: "postgres://postgres:secret@users-db:5432/social_users?sslmode=disable"
