apiVersion: v1
kind: Secret
metadata:
  name: users-app-secret
  namespace: users
  labels:
    stage: config
type: Opaque
stringData:
  ENC_KEY: social-network-secret-key
  DATABASE_URL: "postgres://postgres:secret@users-db-rw:5432/users?sslmode=disable"
