apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
  namespace: frontend
  labels:
    stage: app
    app: nextjs-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
    spec:
      containers:
        - name: nextjs
          image: social-network/front:dev
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: NODE_ENV
              value: production
            - name: GATEWAY
              value: http://api-gateway.api-gateway.svc.cluster.local:8081
            - name: LIVE
              value: http://live.live.svc.cluster.local:8082
            - name: NEXT_PUBLIC_LOG_LEVEL
              value: WARN
            - name: LOG_LEVEL
              value: ERROR
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "alloy.monitoring.svc.cluster.local:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=frontend,service.namespace=social-network,deployment.environment=dev"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
