apiVersion: v1
kind: Service
metadata:
  name: posts-db
  namespace: posts
  labels:
    stage: db
spec:
  selector:
    app: posts-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
