apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  namespace: posts
  labels:
    stage: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z posts-db 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: posts
          image: social-network/posts:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: posts-secret
                  key: DATABASE_URL
