apiVersion: v1
kind: Secret
metadata:
  name: posts-secret
  namespace: posts
  labels:
    stage: config
type: Opaque
stringData:
  POSTGRES_DB: social_posts
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret
  DATABASE_URL: "postgres://postgres:secret@posts-db:5432/social_posts?sslmode=disable"
