apiVersion: v1
kind: Secret
metadata:
  name: posts-app-secret
  namespace: posts
  labels:
    stage: config
type: Opaque
stringData:
  ENC_KEY: social-network-secret-key
  DATABASE_URL: "postgres://postgres:secret@posts-db-rw:5432/posts?sslmode=disable"
