apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: chat-db-monitoring
  namespace: chat
  labels:
    stage: db1
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: chat-db
  podMetricsEndpoints:
  - port: metrics