apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
  labels:
    stage: config
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    otelcol.exporter.otlphttp "victoriametrics" {
      client {
        endpoint = "http://victoria-metrics.monitoring.svc.cluster.local:8428/opentelemetry/"
      }
    }

    otelcol.exporter.otlphttp "victoriaLogs" {
      client {
        endpoint = "http://victoria-logs.monitoring.svc.cluster.local:9428/insert/opentelemetry/"
      }
    }

    otelcol.exporter.otlphttp "victoriaTraces" {
      client {
        endpoint = "http://victoria-traces.monitoring.svc.cluster.local:10428/insert/opentelemetry/"
      }
    }

    otelcol.processor.batch "default" {
      output {
        metrics = [otelcol.exporter.otlphttp.victoriametrics.input]
        logs    = [otelcol.exporter.otlphttp.victoriaLogs.input]
        traces  = [otelcol.exporter.otlphttp.victoriaTraces.input]
      }
    }

    otelcol.processor.memory_limiter "default" {
      check_interval = "1s"
      limit          = "512MiB"

      output {
        metrics = [otelcol.processor.batch.default.input]
        logs    = [otelcol.processor.batch.default.input]
        traces  = [otelcol.processor.batch.default.input]
      }
    }

    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }

      http {
        endpoint = "0.0.0.0:4318"
      }

      output {
        metrics = [otelcol.processor.memory_limiter.default.input]
        logs    = [otelcol.processor.memory_limiter.default.input]
        traces  = [otelcol.processor.memory_limiter.default.input]
      }
    }



      










    