apiVersion: batch/v1
kind: Job
metadata:
  name: media-migrate
  namespace: media
  labels:
    stage: migration
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: social-network/media:dev
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: media-app-secret
                  key: DATABASE_URL
          command: ["sh", "-c"]
          args:
            - |
              ./migrate && \
              echo "Running seeds..." && \
              ./seeds/seed.sh
