apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: redis
  label:
    stage: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:

      initContainers:
        - name: init-sentinel-config
          image: busybox
          command:
            - sh
            - -c
            - |
              cp /config/sentinel.conf /data/sentinel.conf
          volumeMounts:
            - name: sentinel-config
              mountPath: /config
            - name: sentinel-data
              mountPath: /data

      containers:
        - name: redis-sentinel
          image: redis:7.2
          ports:
            - containerPort: 26379
          command:
            - redis-sentinel
            - /data/sentinel.conf
          volumeMounts:
            - name: sentinel-data
              mountPath: /data

      volumes:
        - name: sentinel-config
          configMap:
            name: redis-sentinel-config
        - name: sentinel-data
          emptyDir: {}
