apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: redis
  labels:
    stage: db
spec:
  selector:
    app: redis-sentinel
  ports:
    - port: 26379
      targetPort: 26379
  clusterIP: None