apiVersion: v1
kind: Secret
metadata:
  name: forum-secret
  namespace: forum
  labels:
    stage: config
type: Opaque
stringData:
  POSTGRES_DB: social_users
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret
  DATABASE_URL: "postgres://postgres:secret@forum-db:5432/social_forum?sslmode=disable"
