apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: chat
  labels:
    stage: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      # initContainers:
      #   - name: wait-for-db
      #     image: busybox
      #     command: ['sh', '-c', 'until nc -z chat-db-rw 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: chat
          image: social-network/chat:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chat-db-app
                  key: uri
            - name: ENC_KEY
              value: social-network-secret-key
            - name: GRPC_SERVER_PORT
              value: :50051
            - name: SENTINEL_ADDRS
              value: redis-sentinel.redis.svc.cluster.local:26379
            - name: REDIS_MASTER_SET
              value: "master"
            - name: TELEMETRY_COLLECTOR_ADDR
              value: "localhost:4317"

            - name: USERS_GRPC_ADDR
              value: "users.users.svc.cluster.local:50051"
            - name: POSTS_GRPC_ADDR
              value: "posts.posts.svc.cluster.local:50051"
            - name: CHAT_GRPC_ADDR
              value: "chat.chat.svc.cluster.local:50051"
            - name: NOTIFICATIONS_GRPC_ADDR
              value: "notifications.notifications.svc.cluster.local:50051"
            - name: MEDIA_GRPC_ADDR
              value: "media.media.svc.cluster.local:50051"

            - name: SHUTDOWN_TIMEOUT_SECONDS
              value: "5"
            - name: ENABLE_DEBUG_LOGS
              value: "true"
            - name: ENABLE_SIMPLE_PRINT
              value: "true"
            - name: KAFKA_BROKERS
              value: "kafka.kafka.svc.cluster.local:29092"
            - name: NATS_CLUSTER
              value: "nats://ruser:T0pS3cr3t@nats-client.messaging.svc.cluster.local:4222"


