apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: chat
  labels:
    stage: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z chat-db-rw 5432; do echo waiting for db; sleep 2; done']
      containers:
        - name: chat
          image: social-network/chat:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chat-app-secret
                  key: DATABASE_URL
            - name: ENC_KEY
              valueFrom:
                secretKeyRef:
                  name: chat-app-secret
                  key: ENC_KEY

