apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
  namespace: chat
  labels:
    stage: config
type: Opaque
stringData:
  ENC_KEY: social-network-secret-key
  # DATABASE_URL: "postgres://postgres:secret@chat-db-rw:5432/chat?sslmode=disable"
  DATABASE_URL: "postgres://postgres:secret@chat-db-rw.chat.svc.cluster.local:5432/chat?sslmode=disable"
