apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
  namespace: chat
  labels:
    stage: config
type: Opaque
stringData:
  ENC_KEY: a2F0LWFsZXgtdmFnLXlwYXQtc3RhbS16b25lMDEtZ28=
  DATABASE_URL: "postgres://postgres:secret@chat-db-rw:5432/chat?sslmode=disable"
