# apiVersion: v1
# kind: Secret
# metadata:
#   name: chat-app-secret
#   namespace: chat
#   labels:
#     stage: config
# type: kubernetes.io/basic-auth
# stringData:
#   username: chat
#   password: secret
